# Generated by Django 5.2.17 on 2026-09-19 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='googlecredential',
            name='connected',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='googlecredential',
            name='subject_hash',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
