# Generated by Django 5.2.17 on 2026-09-19 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0002_googlecredential_connected_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sent_signature',
            field=models.TextField(blank=True),
        ),
    ]
