# Generated by Django 5.2.17 on 2026-09-19 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0003_message_sent_signature'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['send_date', 'send_time', 'created_at', 'pk']},
        ),
        migrations.AddField(
            model_name='message',
            name='send_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
