# Generated by Django 5.2.17 on 2026-09-23 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0007_message_imported_from_alter_message_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='imported_recipient_notes',
            field=models.TextField(blank=True, editable=False),
        ),
    ]
