# Generated by Django 5.2.17 on 2026-09-23 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0008_message_imported_recipient_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='contact_match_notes',
            field=models.TextField(blank=True, editable=False),
        ),
    ]
