# Generated by Django 5.2.17 on 2026-09-23 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0009_message_contact_match_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='import_batch',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drafts', to='mail.documentimport'),
        ),
    ]
