# Generated by Django 5.2.17 on 2026-09-24 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0010_message_import_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sent_from',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.CreateModel(
            name='SenderAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('subject_hash', models.CharField(max_length=64)),
                ('encrypted_data', models.TextField()),
                ('connected', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='senders', to='mail.workspace')),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='mail.senderaccount'),
        ),
        migrations.AddConstraint(
            model_name='senderaccount',
            constraint=models.UniqueConstraint(fields=('workspace', 'subject_hash'), name='unique_workspace_sender'),
        ),
    ]
